name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  DEFAULT_PYTHON_VERSION: "3.10"

defaults:
  run:
    shell: bash -l {0}

jobs:
  code_style:
    name: Code Style Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}

      - name: Cache Python Environment
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-pyenv-${{ hashFiles('dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pyenv-

      - name: Install Development Requirements
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r dev-requirements.txt

      - name: Code Style check - Run black
        run: |
          source .venv/bin/activate
          black --check .

      - name: Imports ordering check - Run isort
        run: |
          source .venv/bin/activate
          isort --check .

      - name: Linting check - Run flake8
        run: |
          source .venv/bin/activate
          flake8 .

      - name: Typing check - Run mypy
        run: |
          source .venv/bin/activate
          mypy . --cache-dir=/dev/null

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}

      - name: Cache Python Environment
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-pyenv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pyenv-

      - name: Install Development Requirements
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          source .venv/bin/activate
          make tests
        