name: CI

on:
    pull_request:
      branches:
      - master
    push:
      branches:
      - master

env:
    DEFAULT_PYTHON_VERSION: 3.10

jobs:
  build:
    runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v3

    #   - name: Set up Python 3.10
    #     uses: actions/setup-python@v1
    #     with:
    #       python-version: "3.10"

    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install -r requirements.txt

    #   - name: Test with pytest
    #     run: pytest

    #   - name: Install AF
    #     run: apt install arrayfire

    #   - name: Test array_api
    #     run: python -m pytest arrayfire/array_api

  style:
    name: Code Style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.DEFAULT_PYTHON_VERSION }}

    - name: Install requirements
      run: |
        grep -E '^black' dev-requirements.txt | xargs pip install

    - name: Debug info
      run: |
        pip freeze

    - name: Run black
      run: |
        black --check .
